[package]
name = "wampa"
version = "0.1.0"
authors = ["Sam Perlmutter <sam.perlmutter227@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.12.2"
dotenv = "0.15.0"
chrono = "0.4.38"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }