name: Rust Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-gnu

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wampa
        path: target/x86_64-unknown-linux-gnu/debug/wampa